---
# Production cluster inventory - 9 nodes across 2 DCs

all:
  children:
    cassandra:
      children:
        dc1:
          children:
            dc1_rack1:
              hosts:
                cassandra-dc1-rack1-node1:
                  ansible_host: 10.0.1.11
                cassandra-dc1-rack1-node2:
                  ansible_host: 10.0.1.12
            dc1_rack2:
              hosts:
                cassandra-dc1-rack2-node1:
                  ansible_host: 10.0.1.21
                cassandra-dc1-rack2-node2:
                  ansible_host: 10.0.1.22
            dc1_rack3:
              hosts:
                cassandra-dc1-rack3-node1:
                  ansible_host: 10.0.1.31
                cassandra-dc1-rack3-node2:
                  ansible_host: 10.0.1.32
        dc2:
          children:
            dc2_rack1:
              hosts:
                cassandra-dc2-rack1-node1:
                  ansible_host: 10.0.2.11
            dc2_rack2:
              hosts:
                cassandra-dc2-rack2-node1:
                  ansible_host: 10.0.2.21
            dc2_rack3:
              hosts:
                cassandra-dc2-rack3-node1:
                  ansible_host: 10.0.2.31